---
defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: false

controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: true
        mount: demo-kube
        transitMount: demo-transit
        keyName: vso-client-cache
        kubernetes:
          role: vso-role
          serviceAccount: vault-secrets-operator-controller-manager
          tokenAudiences:
            - vault

